#!/usr/bin/env bash
#Write a Bash script that displays the content of the file /etc/passwd.
while IFS=":" read -r username _ userid _ _ _ homedir _
do
    echo "$username:$userid:$homedir"
done < /etc/passwd
