#!/usr/bin/env bash
#awk
awk '
{ count[$1,$9]++ }
END {
    # Build an array with counts as keys for sorting
    for (key in count) {
        ip_code = key
        split(ip_code, arr, SUBSEP)
        ip = arr[1]
        code = arr[2]
        printf("%s %s %d\n", ip, code, count[key]) | "sort -rn -k3"
    }
}
' apache-access.log | awk '{printf "%5d %s %s\n", $3, $1, $2}'

