#!/bin/bash
# File: 11-manage_my_process

PIDFILE="/var/run/my_process.pid"
SCRIPT="/path/to/manage_my_process"   # Replace with the correct path if needed

case "$1" in
    start)
        $SCRIPT &
        echo $! > $PIDFILE
        echo "manage_my_process started"
        ;;
    stop)
        if [ -f $PIDFILE ]; then
            kill $(cat $PIDFILE)
            rm -f $PIDFILE
            echo "manage_my_process stopped"
        else
            echo "manage_my_process is not running"
        fi
        ;;
    restart)
        if [ -f $PIDFILE ]; then
            kill $(cat $PIDFILE)
            rm -f $PIDFILE
        fi
        $SCRIPT &
        echo $! > $PIDFILE
        echo "manage_my_process restarted"
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        ;;
esac
